### ISSUE TITLE
The submit button, when in mobile doesn't show up as expected as it does on desktop. 

### ISSUE THREAD

**Issue by ceciliallee** [ceciliallee/clovr#1]
https://github.com/ceciliallee/clovr/blob/f71a92a992e253dce90d5ca28eb3db53fe5409c0/css/styles.css#L157-L173
@ansipes 
The submit button shows the default button along with the border

**Comment by andrew-sipes** [comment]
Couple of issues here. One issue is that styling is being applied to the `div` around the `input`, when it should really just be applied directly to the `input`.

https://github.com/ceciliallee/clovr/blob/f71a92a992e253dce90d5ca28eb3db53fe5409c0/questionnaire.html#L229-L230

Additionally, there is a missing closing `div` after line 230.

Recommendations:

- [ ] Remove the style for `.submit` in `styles.css`
- [ ] Move the `submit-button` class to the `input` element
- [ ] Remove the `div` on line 229, or add the closing `div` after line 230
