### ISSUE TITLE
When accessing on mobile (iPhone Safari), the top left logo doesn't show up in expected font

### ISSUE THREAD

**Issue by ceciliallee** [ceciliallee/clovr#2]
https://github.com/ceciliallee/clovr/blob/f71a92a992e253dce90d5ca28eb3db53fe5409c0/questionnaire.html#L17

@ansipes The font shows as times new roman (I think) rather than Montserrat, but extremely confused how because I exported an svg for this...

**Comment by andrew-sipes** [comment]
SVG are written in XML, so they have [elements similar to HTML](https://developer.mozilla.org/en-US/docs/Web/SVG/Element). The error here is similar to if you attempted to style a heading in HTML without loading the required font.

Here is what the text in your SVG looks like under-the-hood:

https://github.com/ceciliallee/clovr/blob/41a81d703dd07aa6c5a690a3e4a6b4d971687809/assets/logohome.svg#L11

To fix this, you'd want to export the SVG again but convert any text elements to paths or "outlines": https://youtu.be/4eF2JPl01_Y?t=33
